import {mkdir,writeFile} from 'node:fs/promises';
import {money} from './policy.mjs';
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export async function report(ledger,directory,research={text:'No research synthesis recorded.',evidence:[]},mode='testnet'){
 await mkdir(directory,{recursive:true}); const rows=ledger.rows(), committed=ledger.committed();
 const paid=rows.filter(r=>r.status==='paid').reduce((n,r)=>n+BigInt(r.amount),0n);
 const snapshot={mode,runId:ledger.runId,createdAt:new Date().toISOString(),policy:ledger.policy,committedBaseUnits:committed.toString(),confirmedPaidBaseUnits:paid.toString(),decisions:rows,research};
 await writeFile(directory+'/decisions.json',JSON.stringify(snapshot,null,2)+'\n');
 await writeFile(directory+'/research.md','# Monsoon research\n\n'+research.text+'\n');
 const table=rows.map(r=>'<tr><td>'+escape(r.endpoint)+'</td><td><span class="tag '+r.status+'">'+escape(r.status)+'</span></td><td>'+money(r.amount)+'</td><td>'+escape(r.reason)+'</td><td>'+(r.tx?'<a href="https://sepolia.basescan.org/tx/'+encodeURIComponent(r.tx)+'" target="_blank" rel="noreferrer">View transaction ↗</a>':'—')+'</td></tr>').join('');
 const card=(label,value)=>'<div class="card"><div class="label">'+label+'</div><div class="value">'+value+'</div></div>';
 const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src &apos;none&apos;; style-src &apos;unsafe-inline&apos;; base-uri &apos;none&apos;"><title>Coin Purse · Run audit</title><style>'+CSS+'</style></head><body><main><header><div class="brand">◉ Coin Purse</div><div class="eyebrow">Research, with boundaries</div></header><p class="eyebrow intro">Run / '+escape(ledger.runId)+'</p><h1>Every decision.<br>Every fraction of a coin.</h1><p class="subtitle">An auditable research purse on Base Sepolia. Payment policy is enforced before signing, outside the language model.</p><div class="banner">'+(mode==='simulation'?'OFFLINE SIMULATION · No real payments or LLM calls. Synthetic research fixtures.':'TESTNET · Only entries marked paid have an independently verified on-chain transfer. Local stall data is synthetic.')+'</div><section class="cards">'+card('Run allowance','$ '+money(ledger.policy.budget))+card('Committed / reserved','$ '+money(committed))+card('Confirmed paid','$ '+money(paid))+card('Refused requests',rows.filter(r=>r.status==='refused').length)+'</section><h2>Decision ledger</h2><div class="tablewrap"><table><thead><tr><th>Endpoint</th><th>Decision</th><th>USDC committed</th><th>Reason</th><th>Receipt</th></tr></thead><tbody>'+table+'</tbody></table></div><h2>Research note</h2><div class="note">'+escape(research.text)+'</div><footer>Per-call ceiling: '+money(ledger.policy.perCall)+' USDC · Integer base units · Persistent SQLite ledger · Failed or uncertain authorizations retain their reservation.</footer></main></body></html>';
 await writeFile(directory+'/audit.html',html); return snapshot;
}
const CSS='*{box-sizing:border-box}body{margin:0;background:#f4f3ec;color:#17352d;font:15px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:42px 28px}header{display:flex;justify-content:space-between;border-bottom:1px solid #cbd4c7;padding-bottom:20px}.brand{font-weight:750;letter-spacing:-.5px;font-size:22px}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:11px}.intro{margin-top:40px}h1{font-size:clamp(32px,5vw,56px);line-height:1.1;letter-spacing:-2px;margin-bottom:12px}.subtitle{color:#617169;max-width:740px}.banner{padding:12px 18px;background:#e5ecd6;border-left:4px solid #809d4a;margin:28px 0}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.card{padding:24px;border:1px solid #cbd4c7;border-radius:12px;background:#fffef7}.value{font-size:27px;font-weight:650;margin-top:12px}.label{color:#617169;font-size:12px;text-transform:uppercase;letter-spacing:1px}h2{font-size:23px;margin-top:36px}.tablewrap{overflow:auto;border:1px solid #cbd4c7;border-radius:12px}table{border-collapse:collapse;width:100%;background:#fffef7;text-align:left}th{background:#e9edde;font-size:11px;text-transform:uppercase;letter-spacing:1px}td,th{padding:15px;border-bottom:1px solid #e3e6dc}td{font-size:13px}.tag{padding:5px 9px;border-radius:20px;background:#e7e8e2;font-size:11px}.refused{background:#f7dfcf;color:#8b3919}.paid{background:#d9efdb;color:#245e30}.uncertain,.reserved{background:#fae8ad}.note{white-space:pre-wrap;background:#fffef7;border:1px solid #cbd4c7;border-radius:12px;padding:24px}a{color:#365d48}footer{margin-top:35px;color:#617169;font-size:12px}@media(max-width:700px){.cards{grid-template-columns:repeat(2,1fr)}main{padding:24px 16px}header{gap:20px}.value{font-size:21px}}';
